[project]
name = "photoorg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.13.0.90",
    "pillow-heif>=1.2.0",
    "ultralytics>=8.4.10",
]
